sudo: required
language: generic

jobs:
  include:
  - dist: jessie
    env: ROS_DISTRO=humble PYTHON=python3

before_install:
  - ln -s $PWD ~/flexbe_ci
  - source ~/flexbe_ci/setup.bash $ROS_DISTRO
  - ~/flexbe_ci/ci_scripts/before_install.bash

install:
  - ~/flexbe_ci/ci_scripts/install.bash

before_script:
  - ~/flexbe_ci/ci_scripts/before_script.bash

script:
  - ~/flexbe_ci/ci_scripts/script.bash
