# This is a basic workflow to help you get started with Actions
name: FlexBE CI
# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  melodic:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04
    env:
      ROS_DISTRO: melodic
      PYTHON: python
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps: &steps
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Prepare CI
        run: |
          ln -s $GITHUB_WORKSPACE ~/flexbe_ci
          source ~/flexbe_ci/setup.bash $ROS_DISTRO
      - name: Install
        run: |
          ~/flexbe_ci/ci_scripts/before_install.bash
          ~/flexbe_ci/ci_scripts/install.bash
      - name: Build and Test
        run: |
          ~/flexbe_ci/ci_scripts/before_script.bash
          ~/flexbe_ci/ci_scripts/script.bash

  noetic:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04
    env:
      ROS_DISTRO: noetic
      PYTHON: python3
    steps: *steps

  kinetic:
    # The type of runner that the job will run on
    runs-on: ubuntu-16.04
    env:
      ROS_DISTRO: kinetic
      PYTHON: python
    steps: *steps
